routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClientController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('client', ClientController::class)->middleware('auth');

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Client;

class City extends Model
{
    use HasFactory;

    protected $table = 'cities';

    protected $fillable = [
        'user_id',
        'cod',
        'name'
    ];

    public function client() {
        return $this->belongsTo(Client::class);
    }

}

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\City;

class Client extends Model
{
    use HasFactory;

    protected $table = 'client';

    protected $fillable = [
        'cod', 'name'
    ];

    public function city() {
        return $this->hasOne(City::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use App\Models\City;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $client = Client::with('city')->paginate(10);

        return view('client.index', ['client' => $client]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'cod' => 'required'
        ]);

        $allInputs = $request->all();

        $client = new Client();
        $client->cod = $allInputs['cod'];
        $client->name = $allInputs['name'];
        $client->save();

        $city = new City();
        $city->cod = $allInputs['cod'];
        $city->name = $allInputs['city'];
        $client->city()->save($city);

        return redirect()->route('client.index')
            ->with('success', 'Client created successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('client.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $request->validate([
            'name' => 'required',
            'cod' => 'required'
        ]);

        $allInputs = $request->all();

        $client = Client::find($allInputs['id']);
        $client->cod = $allInputs['cod'];
        $client->name = $allInputs['name'];
        $client->city->name = $allInputs['city'];
        $client->push();

        return redirect()->route('client.index')
            ->with('success', 'Client created successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();

        return redirect()->route('client.index')
            ->with('success', 'Client deleted successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/client/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @if ($message = Session::get('success'))
                <div class="col-lg-12 alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif

            <div class="col"><h2>Create Clients</h2></div>
            <div class="w-100"></div>
        </div>

        <form method="POST" action="{{ route('client.store') }}">

            @method('POST')
            @csrf

            <table class="table table-bordered" style="width: 97%">
                <tr>
                    <td><label for="cod">COD: </label></td>
                    <td><input name="cod" value=""></td>
                </tr>
                <tr>
                    <td><label for="name">Client Name: </label></td>
                    <td><input name="name" value=""></td>
                </tr>
                <tr>
                    <td><label for="city">City Name: </label></td>
                    <td><input name="city" value=""></td>
                </tr>

                <tr>
                    <td colspan="2">
                        <div class="pull-right h3">
                            <button type="submit" class="btn btn-success">Save Client Record</button>
                        </div>
                    </td>
                </tr>
            </table>

        </form>

    </div>
@endsection

resources/views/client/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @if ($message = Session::get('success'))
                <div class="col-lg-12 alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif

            <div class="col"><h2>Manage Clients</h2></div>
            <div class="w-100"></div>
        </div>

        <form method="POST" action="/client/{{ $client->id }}">

            @method('PUT')
            @csrf

            <table class="table table-bordered" style="width: 97%">

                <tr>
                    <td colspan="2">
                        <input type="hidden" name="id" value="{{ $client->id }}">
                    </td>
                </tr>

                <tr>
                    <td><label for="cod">COD: </label></td>
                    <td><input name="cod" value="{{ $client->cod }}"></td>
                </tr>
                <tr>
                    <td><label for="name">Client Name: </label></td>
                    <td><input name="name" value="{{ $client->name }}"></td>
                </tr>
                <tr>
                    <td><label for="city">City Name: </label></td>
                    <td><input name="city" value="{{ $client->city->name }}"></td>
                </tr>

                <tr>
                    <td colspan="2">
                        <div class="pull-right h3">
                            <button type="submit" class="btn btn-success">Edit Client Record</button>
                        </div>
                    </td>
                </tr>
            </table>

        </form>

    </div>
@endsection

resources/views/client/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            @if ($message = Session::get('success'))
                <div class="col-lg-12 alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif

            <div class="col"><h2>Manage Clients</h2></div>
            <div class="w-100"></div>
            <div class="col">
                <div class="pull-right h3">
                    <a href="{{ route('client.create') }}" class="btn btn-success">Create New Client Record</a>
                </div>
            </div>

            <table class="table table-bordered" style="width: 97%">
                <tr>
                    <th>No</th>
                    <th>COD</th>
                    <th>Name</th>
                    <th>City</th>
                    <th>Action</th>
                </tr>

                @foreach($client as $key => $data)

                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $data->cod }}</td>
                        <td>{{ $data->name }}</td>
                        <td>{{ $data->city->name }}</td>
                        <td>
                            <form action="{{ route('client.destroy', $data->id) }}" method="POST">
                                <a href="{{ route('client.edit', $data->id) }}" class="btn btn-primary">Edit</a>

                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>

                @endforeach

                {{ $client->links() }}
            </table>

        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Customer Management Application') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>